// generated by vite-plugin-components
// read more https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AddForm: typeof import('./src/components/AddForm.vue')['default']
    Calendar: typeof import('./src/components/Calendar.vue')['default']
    ColorSelector: typeof import('./src/components/ColorSelector.vue')['default']
    Dropdown: typeof import('./src/components/Dropdown.vue')['default']
    Modal: typeof import('./src/components/Modal.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    Searchbar: typeof import('./src/components/Searchbar.vue')['default']
    Sidebar: typeof import('./src/components/Sidebar.vue')['default']
    Timeline: typeof import('./src/components/Timeline.vue')['default']
    Timer: typeof import('./src/components/Timer.vue')['default']
    ValueSelector: typeof import('./src/components/ValueSelector.vue')['default']
  }
}

export { }
