// generated by vite-plugin-components
// read more https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Calendar: typeof import('./src/components/Calendar.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    Sidebar: typeof import('./src/components/Sidebar.vue')['default']
  }
}

export { }
